shopping_app/product/urls.py
from django.urls import path
from django.conf.urls import url
from . import views,models
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView

app_name = "product"
urlpatterns = [
    url(r'home', views.IndexView.as_view(),name='home'),
    path('shop/', views.ShopView.as_view(), name='shop'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('cart/', views.CartListView.as_view(), name='cart'),
    path('add/', views.add_to_cart, name='add'),
    path('<int:cart_id>/update', views.update_cart, name='update_cart'),
    path('<int:cart_id>/delete', views.delete_cart, name='remove_cart_product'),
    path('checkout/', TemplateView.as_view(template_name='product/checkout.html'), name='checkout'),
    path('payment/', views.payment, name='payment'),
    path('order/', login_required(views.OrderListView.as_view()), name='order'),
    path('<int:pk>/order', login_required(views.OrderDetailView.as_view()), name='order_detail'),
    path('<int:pk>/invoice', login_required(views.GeneratePdf.as_view()), name='invoice'),
]

shopping_app/shopping_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings 
from django.conf.urls.static import static 
from django.conf.urls import url, include
from django.views.generic import TemplateView
from allauth.account import views
from product import views as product_view

urlpatterns = [
    path('', product_view.IndexView.as_view(),name='home'),
    url(r'^accounts/login/', views.login, name="account_login"),
    url(r'^accounts/signup/', views.signup, name="account_signup"),
    url(r'^accounts/', include('allauth.urls')),
    path('mall/', include("product.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

shopping_app/product/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    mobile=models.BigIntegerField(null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    updated_at:models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'user'

class ModelBase(models.Model):
    created_at = models.DateTimeField(auto_now_add=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,null=True)

    class Meta:
        abstract = True
        managed = False

class Product(ModelBase):
    name = models.CharField(max_length=200)
    mrp=models.IntegerField()
    stock=models.IntegerField(default=0)
    image=models.ImageField(upload_to='images',default=None)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'product'

class Cart(ModelBase):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()

    def __str__(self):
        return self.user.username+" cart"

    class Meta:
        db_table = 'cart'

class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    status=models.CharField(max_length=20)
    created_at=models.DateTimeField(auto_now_add=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,null=True)
    arrived_at=models.DateTimeField(default=None)
    amount=models.IntegerField()
    ref_code=models.CharField(max_length=20)

    def __str__(self):
        return self.user.username+" order"

    class Meta:
        db_table = 'order'

class OrderDetails(ModelBase):
    order=models.ForeignKey(Order,on_delete=models.SET_NULL,null=True)
    product=models.ForeignKey(Product,on_delete=models.SET_NULL,null=True)
    quantity=models.IntegerField()

    class Meta:
        db_table = 'order_details'

class Transaction(models.Model):
    token = models.CharField(max_length=120)
    order=models.ForeignKey(Order,on_delete=models.SET_NULL,null=True)
    success = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.order

    class Meta:
        db_table = 'transaction'
        ordering = ['-timestamp']

shopping_app/product/views.py
from django.shortcuts import get_object_or_404, render,redirect
from django.conf import settings
from django.contrib import messages
from django.views import generic
from django.urls import reverse
from .models import Product,Cart,User,Order,OrderDetails,Transaction
from django.http import HttpResponseRedirect,HttpResponse
from .extras import generate_order_id
import stripe
import json
from django.db.models import Sum
from django.db import transaction
from django.contrib.auth.decorators import login_required
import logging
from django.core.mail import send_mail
from .utils import render_to_pdf
from datetime import datetime
logger = logging.getLogger(__name__)
stripe.api_key = settings.STRIPE_SECRET_KEY
# Create your views here.

class IndexView(generic.ListView):
    model = Product
    template_name = 'product/home.html'
    context_object_name = 'product_list'

class ShopView(generic.ListView):
    model = Product
    template_name = 'product/shop.html'
    context_object_name = 'product_list'

class DetailView(generic.DetailView):
    model = Product
    template_name = 'product/detail.html'
    context_object_name = 'product_details'
    
    def get_template_names(self):
        if self.request.is_ajax():
            template_name = 'product/partial-details.html'
        else:
            template_name = 'product/detail.html'
        return [template_name]
    # def get_queryset(self):
    #     if self.request.user.id!=None:
    #         user = self.request.user.id
    #         print(user)
    #         print(self.kwargs)
    #         return Product.objects.filter(id=self.kwargs["pk"])
            
            
    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        if self.request.user.id!=None:
            cart=Cart.objects.prefetch_related('user').filter(user_id=self.request.user.id)
            for item in cart:
                if item.product.id==self.kwargs["pk"]:
                    context['cart']=True
                    return context
            context['cart']=False
        return context

class CartListView(generic.ListView):
    model = Cart
    template_name = 'product/cart.html'
    context_object_name = 'cart_list'

    def get_queryset(self):
        if self.request.user.id!=None:
            return Cart.objects.filter(user=self.request.user.id)
        else:
            if 'cart' in self.request.GET :
                data=json.loads(self.request.GET['cart'])
                self.request.session['cart']=data
                return data
            else:
                return []

    def get_template_names(self):
        if self.request.is_ajax():
            template_name = 'product/partial-cart.html'
        else:
            template_name = 'product/cart.html'
        return [template_name]


def add_to_cart(request):
    if request.user.id!=None:
        if request.method == 'POST':
            cart=Cart.objects.create(product=Product.objects.get(pk=request.POST['product']),user=User.objects.get(pk=request.user.id),quantity=1)
            cart.save()
            return HttpResponseRedirect(reverse('product:detail', args=(request.POST['product'],)))
            # return render(request, 'product/partial-details.html')
    else:
        return HttpResponseRedirect(reverse('product:detail', args=(request.POST['product'],)))

def update_cart(request, cart_id):
    if request.user.id!=None:
        cart = get_object_or_404(Cart, pk=cart_id)
        cart.quantity = request.POST['quantity']
        cart.save()
        return HttpResponseRedirect(reverse('product:cart'))

def delete_cart(request, cart_id):
    cart = get_object_or_404(Cart, pk=cart_id)
    cart.delete()
    return HttpResponseRedirect(reverse('product:cart'))

@login_required
def payment(request):
    if('cart' in request.session and request.session['cart']!=None):
        for item in request.session['cart']:
            Cart.objects.create(user=User.objects.get(pk=request.user.id),product=Product.objects.get(pk=item['id']),quantity=item['quantity'])
        request.session['cart']=None
        return HttpResponseRedirect(reverse('product:cart'))

    cart=Cart.objects.filter(user=request.user.id)
    amount=0
    for item in cart:
        amount+=item.product.mrp*item.quantity
    publishKey = settings.STRIPE_PUBLISHABLE_KEY
    if request.method == 'POST':
        token = request.POST.get('stripeToken', False)
        try:
            charge = stripe.Charge.create(
                amount=amount*100,
                currency='usd',
                description='Example charge',
                source=token,
            )
            return checkout(request,token=token)
        except stripe.error.CardError as e:
            messages.info(request, "Your card has been declined.")
    return HttpResponseRedirect(reverse('product:cart'))


@login_required
@transaction.atomic
def checkout(request,token):
    cart=Cart.objects.filter(user=request.user.id)
    if len(cart)!=0:
        amount=0
        for item in cart:
            amount+=item.product.mrp*item.quantity
        order=Order.objects.create(user=User.objects.get(pk=request.user.id),amount=amount,ref_code=generate_order_id(),status="processing")
        order.save()
        order_details=[]
        for item in cart:
            order_details.append(OrderDetails(order=order,product=item.product,quantity=item.quantity))
        cart.delete()
        OrderDetails.objects.bulk_create(order_details)
        trans=Transaction.objects.create(token=token,order=order)
        if trans:
            subject = 'Order Confirmation'
            message = ' Thank you for order '
            email_from = settings.EMAIL_HOST_USER
            recipient_list = ['mayankchhabra2527@gmail.com',]
            send_mail( subject, message, email_from, recipient_list )
        return HttpResponseRedirect(reverse('product:order'))
    else:
        return HttpResponseRedirect(reverse('product:home'))

class OrderListView(generic.ListView):
    model = Order
    template_name = 'product/order.html'
    context_object_name = 'order_list'

class OrderDetailView(generic.DetailView):
    model = Order
    template_name = 'product/order_detail.html'
    context_object_name = 'order'

class GeneratePdf(generic.View):
    context_object_name = 'order'

    def get(self, request, *args, **kwargs):
        data=Order.objects.get(pk=self.kwargs["pk"])
        pdf = render_to_pdf('product/invoice.html', {'order':data})
        return HttpResponse(pdf, content_type='application/pdf')

shopping_app/product/templates/product/cart.html
{% extends "account/base.html" %}
{% load static %}
{% load mathfilters %}
{% block head_links %} 

<title>Cart</title>
<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">

{% endblock %}

{% block content %}
<!-- <div class="container-fluid" style="margin: 200px 0px">
        <center><h2>Your Cart</h2>
            <br>
{% if cart_list|length == 0%}
<center><h3>Cart is Empty!</h3></center>
{% else %}
<table border="1px" style="width:600px;text-align: center;">
    <tr>
        <td>Product</td>
        <td>MRP</td>
        <td>Cost</td>
        <td>Quantity</td>
        <td>Remove Item</td>
    </tr>
    {% for item in cart_list %}
    <tr>
        <td>{{item.product}}</td>
        {% if not user.is_authenticated %}
        <td>{{item.mrp}}</td>
        <td class="cost">{{item.mrp|mul:item.quantity}}</td>
        {%else%}
        <td>{{item.product.mrp}}</td>
        <td class="cost">{{item.product.mrp|mul:item.quantity}}</td>
        {%endif%}
        <td>
        {% if user.is_authenticated %}
        <form action="{% url 'product:update_cart' item.id %}" method="post">
            {% csrf_token %}
            <select name="quantity">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
              </select> &nbsp;
            <button>Update</button>
        </form>
        {%else%}
        <select name="quantity">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
        </select>
        <button class="update" onclick="update('{{item.id}}',this)">Update</button>
        {%endif%}
    </td>
    <td>
    {% if user.is_authenticated %}
        <form action="{% url 'product:remove_cart_product' item.id %}" method="post">
            {% csrf_token %}
            <button>Remove product</button>
        </form>
    {%else%}
        <button  onclick="remove('{{item.id}}')">Remove product</button>
    {%endif%}
    </td>
    </tr>
    {% endfor %}
</table>

<p>Total - Rs <span id="total"></span></p>
    
    <p><button onclick="checkout()">Checkout</button></p>
    {% endif %}

</center>
</div> -->



   <!-- Start Banner Area -->
   <section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Shopping Cart</h1>
                <nav class="d-flex align-items-center">
                    <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                    <a href="category.html">Cart</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->
<div id="main">
    {% include "product/partial-cart.html" %}
</div>

<script>
    function checkout() {
        localStorage.clear();
        window.location.href="{% url 'product:checkout' %}";
    }
</script>


<script>
    function update(id,obj) {
        let quantity = $(obj).siblings()[1].childNodes[0].innerText;
        // console.log(obj.previousElementSibling.value)
        let cart=JSON.parse(localStorage.getItem("cart"))
        cart.forEach(element => {
            if(element.id==id){
                element.quantity=quantity
            }            
        }); 
        localStorage.setItem('cart',JSON.stringify(cart))
        window.location.href="{% url 'product:cart' %}?cart="+localStorage.getItem("cart")
    }

    function remove(id,obj){
        let cart=JSON.parse(localStorage.getItem("cart"))
        cart=cart.filter(item=>{
            if(item.id!=id) return item;
        })
        localStorage.setItem('cart',JSON.stringify(cart))
        window.location.href="{% url 'product:cart' %}?cart="+localStorage.getItem("cart")
    }
</script>


<script>
    function updateCart(obj,id) {
        quantity=$(obj).siblings()[1].childNodes[0].innerText;
        $.ajax({
            url:'/mall/'+id+'/update',
            type: "POST",
            data: {quantity:quantity,csrfmiddlewaretoken: '{{ csrf_token }}'},
            success: function(resultData) { 
                $('#main').html(resultData);
                alert('success')
                $('select').niceSelect();
            }
        })
    }

    function deleteCart(id) {
        $.ajax({
            url:'/mall/'+id+'/delete',
            type: "POST",
            data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
            success: function(resultData) { 
                $('#main').html(resultData);
                $('select').niceSelect();
            }
        })
    }



</script>
<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>

<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
{% endblock %}

shopping_app/product/templates/product/detail.html
{% extends "account/base.html" %}
{% load static %}
{% block head_links %} 

<title>Details</title>

{% endblock %}

{% block content %}
<!-- <div class="container-fluid">
<h3>{{product_details.name}}</h3>
<ul>
    <li>Cost - {{product_details.mrp}}</li>
    <img width="200px" height="200px" src="{{product_details.image.url}}" alt="Not Found">
    {% if not user.is_authenticated %}
    <div>
        <button onclick='addToCart("{{product_details.id}}",this)' id="add">Add to Cart</button>
        <a href="#" onclick="viewCart()" style="display: none" id="cart">View Cart</a>
    </div>
    {% else %}
        <form action="{% url 'product:add' %}" method="post">
            {% csrf_token %}
            <input type="text" hidden name="product" value="{{product_details.id}}">
            <button id="add">Add to Cart</button>
        </form>
        <a href="{% url 'product:cart' %}" style="display: none" id="cart">View Cart</a>
    {% endif %}


</ul>
</div> -->

<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
            <div class="container">
                <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                    <div class="col-first">
                        <h1>Product Details Page</h1>
                        <nav class="d-flex align-items-center">
                            <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                            <a href="#">Shop<span class="lnr lnr-arrow-right"></span></a>
                            <a href="single-product.html">product-details</a>
                        </nav>
                    </div>
                </div>
            </div>
        </section>
<!-- End Banner Area -->
    
{% include "product/partial-details.html" %}

{% if not user.is_authenticated %}
<script>
    if(localStorage.getItem("cart")){
        let cart=JSON.parse(localStorage.getItem("cart"))
        cart.forEach(element => {
            if(element.id=="{{product_details.id}}"){
                document.getElementById('add').style.display="none";
                document.getElementById('cart').style.display="inline";
            }            
        });
        // document.getElementById('add').style.display="none";
        // document.getElementById('cart').style.display="inline";
    }
    function viewCart() {
            if(localStorage.getItem("cart")){
            window.location.href="{% url 'product:cart' %}?cart="+localStorage.getItem("cart")
            }else{
            window.location.href="{% url 'product:cart' %}"
            }
    }   

    function addToCart(id,btn) {
        console.log(id)
        cart=[]
        if(localStorage.getItem("cart")){
            cart=JSON.parse(localStorage.getItem("cart"))
            cart.push({
                product:"{{product_details.name}}",
                id:"{{product_details.id}}",
                mrp:"{{product_details.mrp}}",
                quantity:1
            })
        }
        else{
            cart.push({
                product:"{{product_details.name}}",
                id:"{{product_details.id}}",
                mrp:"{{product_details.mrp}}",
                quantity:1
            })
        }
        localStorage.setItem('cart',JSON.stringify(cart))
        btn.style.display="none"
        document.getElementById('cart').style.display="inline";
    }
</script>

{% endif %}

<script>
    function addcart() {
        $.ajax({
            url:"{% url 'product:add' %}",
            type: "POST",
            data: {product:$("#p_id").val(),csrfmiddlewaretoken: '{{ csrf_token }}'},
            success: function(resultData) { 
                alert("Sucess");
                $('#main').html(resultData);
    
            }
        })
    }
</script>
    
{% endblock %}

shopping_app/product/templates/product/invoice.html
{% load mathfilters %}

<html>
    <head>
        <title>Title</title>
        <style type="text/css">
            body {
                font-weight: 200;
                font-size: 14px;
            }
            .header {
                font-size: 20px;
                font-weight: 100;
                text-align: center;
                color: #007cae;
            }
            .title {
                font-size: 22px;
                font-weight: 100;
               /* text-align: right;*/
               padding: 10px 20px 0px 20px;  
            }
            .title span {
                color: #007cae;
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                /*margin-left: 40%;*/
            }
            .hrItem {
                border: none;
                height: 1px;
                /* Set the hr color */
                color: #333; /* old IE */
                background-color: #fff; /* Modern Browsers */
            }
            .total{
                text-align: right;
            }
        </style>
    </head>
    <body>
        <div class='wrapper'>
            <div class='header'>
                <p class='title'>Invoice #{{order.ref_code}} </p>
            </div>
            <p>Date {{order.created_at}} </p>
        <div>
        <center>
            <div class='details'>
                <table border="1px" style="width:400px;text-align: center;">
                    <tr>
                        <td>Product</td>
                        <td>MRP</td>
                        <td>quantity</td>
                        <td>Cost</td>
                    </tr>
                    {% for item in order.orderdetails_set.all %}
                    <tr>
                        <td>{{item.product}}</td>
                        <td>{{item.product.mrp}}</td>        
                        <td>{{item.quantity}}</td>        
                        <td>{{item.product.mrp|mul:item.quantity}}</td>        
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </center>
    </div>
    <div class='header'>
        <p class='title'>
             <span class="total">Total - Rs {{order.amount}} </span>
        </p>
    </div>
</body>
</html>

shopping_app/product/templates/product/order.html
{% extends "account/base.html" %}

{% block head_links %} 

<title>Order</title>

{% endblock %}

{% block content %}

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1>Order</h1>
                    <nav class="d-flex align-items-center">
                        <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                        <a href="category.html">Fashon Category</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->
    
<div class="container-fluid">

    <center>
        <br>
{% if order_list|length == 0%}
<center><h3>No orders</h3></center>
{% else %}
<table border="1px" style="width:600px;text-align: center;">
    <tr>
        <td>Date</td>
        <td>Reference Code</td>
        <td>Amount</td>
        <td>Status</td>
        <td>View Details</td>
    </tr>
    {% for item in order_list %}
    <tr>
        <td>{{item.created_at}}</td>
        <td>{{item.ref_code}}</td>
        <td>{{item.amount}}</td>        
        <td>{{item.status}}</td>        
        <td><a href="{% url 'product:order_detail' item.id %}"><button>View Order Details</button></a></td>        
    </tr>
    {% endfor %}
</table>
</div>
<br>
{% endif %}
{% endblock %}

shopping_app/product/templates/product/order_detail.html
{% extends "account/base.html" %}
{% load mathfilters %}
{% block head_links %} 

<title>Order Details</title>

{% endblock %}

{% block content %}
<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1>Order Tracking</h1>
                    <nav class="d-flex align-items-center">
                        <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                        <a href="category.html">Fashon Category</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->
 
    <div>
        <a style="float: right;margin: 20px;" href="{% url 'product:invoice' order.id %}"><button>Download Invoice</button></a>
    </div>

<div class="container-fluid" style="margin: 80px 0;">
<center>
    <br>
    <p>Invoice #{{order.ref_code}} </p>
    <table border="1px" style="width:600px;text-align: center;">
        <tr>
            <td>Product</td>
            <td>MRP</td>
            <td>quantity</td>
            <td>Cost</td>
        </tr>
        {% for item in order.orderdetails_set.all %}
        <tr>
            <td>{{item.product}}</td>
            <td>{{item.product.mrp}}</td>        
            <td>{{item.quantity}}</td>        
            <td>{{item.product.mrp|mul:item.quantity}}</td>        
        </tr>
        {% endfor %}
    </table>
    <p>Total - Rs {{order.amount}} </p>
    <p>Status - {{order.status}} </p>
</center>
</div>

{% endblock %}

shopping_app/product/templates/product/partial-cart.html
{% load mathfilters %}
{% load static %}

<!--================Cart Area =================-->
<section class="cart_area">
    <div class="container">
        <div class="cart_inner">
        <div class="table-responsive">
        {% if cart_list|length == 0%}
        <center><h3>Cart is Empty!</h3></center>
        {% else %}
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Product</th>
                            <th scope="col">MRP</th>
                            <th scope="col">Cost</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Remove Item</th>
                        </tr>
                    </thead>
                    <tbody>
                       {% for item in cart_list %}
                        <tr>
                            <td>
                                <div class="media">
                                    <div class="d-flex">
                                        <img src="{{item.product.image.url}}" alt="">
                                    </div>
                                    <div class="media-body">
                                        <p>{{item.product}}</p>
                                    </div>
                                </div>
                            </td>
                            {% if not user.is_authenticated %}
                            <td>{{item.mrp}}</td>
                            <td class="cost">{{item.mrp|mul:item.quantity}}</td>
                            {%else%}
                            <td>{{item.product.mrp}}</td>
                            <td class="cost">{{item.product.mrp|mul:item.quantity}}</td>
                            {%endif%}
                            <td>
                                <div>
                                        {% if user.is_authenticated %}
                                        <!-- <form action="{% url 'product:update_cart' item.id %}" method="post">
                                            {% csrf_token %} -->
                                            <select name="quantity">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                              </select>
                                            <button class="update" onclick="updateCart(this,'{{item.id}}')">Update</button>
                                        <!-- </form> -->
                                        {%else%}
                                        <select name="quantity">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                        </select>
                                        <button class="update" onclick="update('{{item.id}}',this)">Update</button>
                                        {%endif%}                                
                                    </div>
                            </td>
                            <td>
                                    {% if user.is_authenticated %}
                                        <!-- <form action="{% url 'product:remove_cart_product' item.id %}" method="post"> -->
                                            <!-- {% csrf_token %} -->
                                            <button onclick="deleteCart('{{item.id}}')">Remove product</button>
                                        <!-- </form> -->
                                    {%else%}
                                        <button  onclick="remove('{{item.id}}')">Remove product</button>
                                    {%endif%}
                             </td>
    {% endfor %}

                        </tr>
                        
                        <tr class="out_button_area">
                            <td>

                            </td>
                            <td>

                            </td>
                            <td>

                            </td>
                            <td>
                                <div class="checkout_btn_inner d-flex align-items-center">
                                        <p>Total - Rs <span id="total"></span></p>
                                    </div>
                                </td>
                                    <td>
                                        {% if user.is_authenticated %}
                                        <p><button onclick="checkout()">Checkout</button></p>
                                 {%else%} 
                                        <P>Please <a href="/accounts/login">Login</a> to checkout</P>
                                        {%endif%}
                            </td>
                        </tr>
                    </tbody>
                </table>
                {% endif %}
            </div>
        </div>
    </div>
</section>
<!--================End Cart Area =================-->
<script>
    select_element=document.getElementsByTagName('select')
</script>
{% for item in cart_list %}
<script>
    select_element['{{forloop.counter0}}'].value='{{item.quantity}}';
</script>
{%endfor%}
<script>
    cost_elemtnts=document.getElementsByClassName('cost')
    sum=0;
    for(i=0;i<cost_elemtnts.length;i++){
        sum+=Number(cost_elemtnts[i].textContent)
    }
    document.getElementById('total').textContent=sum
</script>
    